#!/usr/bin/env python
"""
VoxBox - IoT project for Intel Edison

https://github.com/Dominiol/VoxBox
"""

import config, git, imp, os, subprocess, sys
from devices import LcdDisplay

home_path = os.getcwd()
loaded_modules = []

lcdDisplay = LcdDisplay()

def load_all_modules():
    print 'Loading modules...'
    for file in os.listdir('modules'):
        if file.endswith('.py'):
            module_name = os.path.basename(file)[:-3]
            filename = os.path.join(home_path, 'modules', file)
            module = imp.load_source(module_name, filename)
            
            for name, obj in vars(module).iteritems():
                if hasattr(obj, 'pattern'):
                    loaded_modules.append(obj)
                    print '%s loaded' % (name)
    print '%s modules loaded!' % (len(loaded_modules))

def main():
    load_all_modules()
    lcdDisplay.writeText('Working!')
    lcdDisplay.changeColor(0, 255, 255)
    lcdDisplay.changeColor(255, 128, 0)
    lcdDisplay.changeColor(0, 0, 0)
    lcdDisplay.changeColor(255, 255, 255)
    lcdDisplay.darken(0.5)
    lcdDisplay.lighten(0.5)
    
    while True:
        # main loop
        pass

if __name__ == '__main__': 
   main()